import { StyleSheet } from "react-native";

export const colors = {
  primary: "#E3965A",
  border: "#ddd",
  borderSoft: "#eee",
  bgSoft: "#fafafa",
  textMuted: "#666",
};

export const uploadStyles = StyleSheet.create({
  container: { padding: 16, alignItems: "center" },
  title: { fontSize: 18, fontWeight: "bold", alignSelf: "center" },
  sectionTitle: { fontSize: 16, fontWeight: "600", alignSelf: "flex-end", marginBottom: 8 },
  label: { alignSelf: "flex-end", marginBottom: 6 },
  input: {
    width: "100%",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 12,
    backgroundColor: "white",
  },
  placesInput: {
    height: 48,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 10,
    fontSize: 16,
    textAlign: "right",
    backgroundColor: "white",
  },
  placesListView: {
    position: "absolute",
    top: 50,
    zIndex: 1000,
    elevation: 5,
    backgroundColor: "white",
    width: "100%",
  },
  imageBox: {
    height: 150,
    width: "100%",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
    backgroundColor: colors.bgSoft,
  },
  cameraButton: { flexDirection: "row", alignItems: "center", marginBottom: 16 },
  previewImage: { height: 100, width: 100, borderRadius: 8 },
  removeButton: {
    position: "absolute",
    top: 2,
    right: 2,
    backgroundColor: "rgba(255,0,0,0.85)",
    borderRadius: 12,
    width: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
  },
  typeRow: { flexDirection: "row", justifyContent: "space-around", width: "100%", marginBottom: 12 },
  typeOption: {
    alignItems: "center",
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    width: 90,
    backgroundColor: "white",
  },
  selectedType: { borderColor: colors.primary, backgroundColor: "#FDEAD7" },
  booleanRow: { flexDirection: "row", justifyContent: "space-between", width: "100%", gap: 8, marginVertical: 8 },
  toggleChip: {
    flexDirection: "row-reverse",
    alignItems: "center",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    flex: 1,
  },
  propertyTypeList: {
    flexDirection: "row-reverse",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    gap: 8,
    marginTop: 8,
    marginBottom: 12,
  },
  propertyTypeButton: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 14,
    backgroundColor: "#f7f7f7",
  },
  selectedPropertyType: { borderColor: colors.primary, backgroundColor: "#FDEAD7" },
  progressHeader: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 8, backgroundColor: "white" },
  progressBarOuter: { height: 6, backgroundColor: colors.borderSoft, borderRadius: 999, marginTop: 10 },
  progressBarInner: { height: 6, backgroundColor: colors.primary, borderRadius: 999 },
  progressText: { marginTop: 6, textAlign: "center", color: colors.textMuted },
  bottomBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    padding: 12,
    backgroundColor: "white",
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: colors.borderSoft,
  },
  primaryBtn: { flex: 1, backgroundColor: colors.primary, paddingVertical: 14, borderRadius: 12, alignItems: "center" },
  primaryBtnText: { color: "white", fontWeight: "700" },
  secondaryBtn: { flex: 1, backgroundColor: "#F2F2F2", paddingVertical: 14, borderRadius: 12, alignItems: "center" },
  secondaryBtnText: { color: "#333", fontWeight: "600" },
});