import { StyleSheet } from "react-native";

export const colors = {
  primary: "#E3965A",
  border: "#ddd",
  borderSoft: "#eee",
  bgSoft: "#fafafa",
  textMuted: "#666",
};

export const uploadStyles = StyleSheet.create({
  container: { padding: 16, alignItems: "center" },
  title: { fontSize: 18, fontWeight: "bold", alignSelf: "center" },
  sectionTitle: { fontSize: 16, fontWeight: "600", alignSelf: "flex-end", marginBottom: 8 },
  label: { alignSelf: "flex-end", marginBottom: 6 },
  input: {
    width: "100%",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 12,
    backgroundColor: "white",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSoft,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#111",
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  backButtonText: {
    fontSize: 24,
    color: colors.primary,
    fontWeight: "bold",
  },
  stepContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  stepContent: {
    paddingBottom: 180,
  },
  stepHeader: {
    marginBottom: 24,
    alignItems: "flex-end",
  },
  stepTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#111",
    marginBottom: 8,
    textAlign: "right",
  },
  stepDescription: {
    fontSize: 14,
    color: colors.textMuted,
    textAlign: "right",
    lineHeight: 20,
  },
  placesInput: {
    height: 48,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 10,
    fontSize: 16,
    textAlign: "right",
    backgroundColor: "white",
  },
  placesListView: {
    position: "absolute",
    top: 50,
    zIndex: 1000,
    elevation: 5,
    backgroundColor: "white",
    width: "100%",
  },
  imageBox: {
    height: 200,
    width: "100%",
    borderWidth: 2,
    borderColor: colors.borderSoft,
    borderStyle: "dashed",
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
    backgroundColor: colors.bgSoft,
  },
  cameraButton: { flexDirection: "row", alignItems: "center", marginBottom: 16 },
  previewImage: { height: 120, width: 120, borderRadius: 12 },
  actionButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: "#fff",
    borderWidth: 1.5,
    borderColor: colors.primary,
    gap: 8,
  },
  actionButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.primary,
  },
  removeButton: {
    position: "absolute",
    top: 2,
    right: 2,
    backgroundColor: "rgba(255,0,0,0.85)",
    borderRadius: 12,
    width: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
  },
  typeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 12,
    gap: 12,
  },
  typeOption: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 20,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: colors.borderSoft,
    backgroundColor: "white",
    minHeight: 140,
    justifyContent: "center",
  },
  selectedType: {
    borderColor: colors.primary,
    backgroundColor: "#FEF5ED",
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  iconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.bgSoft,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  iconContainerActive: {
    backgroundColor: "#FDEAD7",
  },
  typeText: {
    fontSize: 15,
    fontWeight: "500",
    color: colors.textMuted,
    textAlign: "center",
  },
  typeTextActive: {
    color: colors.primary,
    fontWeight: "700",
  },
  booleanRow: { flexDirection: "row", justifyContent: "space-between", width: "100%", gap: 8, marginVertical: 8 },
  toggleChip: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    borderWidth: 2,
    borderColor: colors.borderSoft,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    flex: 1,
    minHeight: 50,
  },
  selectedToggleChip: {
    backgroundColor: "#FEF5ED",
    borderColor: colors.primary,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  toggleChipText: {
    marginHorizontal: 8,
    fontSize: 14,
    fontWeight: "500",
    color: colors.textMuted,
  },
  selectedToggleChipText: {
    color: colors.primary,
    fontWeight: "700",
  },
  propertyTypeList: {
    flexDirection: "row-reverse",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    gap: 8,
    marginTop: 8,
    marginBottom: 12,
  },
  propertyTypeButton: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 14,
    backgroundColor: "#f7f7f7",
  },
  selectedPropertyType: { borderColor: colors.primary, backgroundColor: "#FDEAD7" },
  progressHeader: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 8, backgroundColor: "white" },
  progressBarOuter: { height: 6, backgroundColor: colors.borderSoft, borderRadius: 999, marginTop: 10 },
  progressBarInner: { height: 6, backgroundColor: colors.primary, borderRadius: 999 },
  progressText: { marginTop: 6, textAlign: "center", color: colors.textMuted },
  bottomBar: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
    backgroundColor: "white",
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: colors.borderSoft,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 5,
    zIndex: 10,
  },
  primaryBtn: { flex: 1, backgroundColor: colors.primary, paddingVertical: 14, borderRadius: 12, alignItems: "center" },
  primaryBtnText: { color: "white", fontWeight: "700" },
  secondaryBtn: { flex: 1, backgroundColor: "#F2F2F2", paddingVertical: 14, borderRadius: 12, alignItems: "center" },
  secondaryBtnText: { color: "#333", fontWeight: "600" },
});